"""empty message

Revision ID: 43ee06cd78d4
Revises: 
Create Date: 2025-09-09 09:10:46.811987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ee06cd78d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_endpoint', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('relay_endpoint', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('relay_endpoint')
        batch_op.drop_column('data_endpoint')

    # ### end Alembic commands ###
